target 'doctor' do
pod 'AFNetworking',’~> 3.2.1’
pod 'UMCAnalytics'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
  # U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'
## 集成微信(完整版14.4M)
#pod 'UMCShare/Social/WeChat'
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMCShare/Social/QQ'
#pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
